### ISSUE TITLE
How to customize a color?

### ISSUE THREAD

**Issue by BarbzYHOOL** [dracula/sublime#30]
Hello @zenorocha how can I change the "selection highlight" color? I want it to stand out more, like pink

thx

**Comment by BarbzYHOOL** [comment]
```yml
"globals":
    {
        "selection": "darkslategrey",
    },
```

found it
